**CONVERSTION : FROM OTHER PYHTON STRUCTURES TO NUMPY STRUCTURE**

In [1]:
import numpy as np

In [2]:
import sklearn

In [3]:
myarr1 = np.array([1,2,3,4,5,6,7,8,9,100], np.int32)

In [4]:
myarr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100], dtype=int32)

In [5]:
myarr1.shape

(10,)

In [6]:
myarr = np.array([[1,2,3,4,5,6,7,8,9,101]], np.int32)

In [7]:
myarr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9, 101]], dtype=int32)

In [8]:
myarr.shape


(1, 10)

In [9]:
myarr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

In [10]:
myarr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
myarr2.shape

(4, 5)

In [12]:
 myarr.dtype

dtype('int32')

In [13]:
myarr2[3,4] = 28

In [14]:
myarr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 28]])

In [16]:
  myarr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9, 101]], dtype=int32)

In [17]:
myarr2.size

20

In [24]:
  myarr3 = np.array({34,35,36,37,38})

In [29]:
np.array({34,34,34})

array({34}, dtype=object)

Data type   Description
bool_   Boolean (True or False) stored as a byte
int_    Default integer type (same as C long; normally either int64 or int32)
intc    Identical to C int (normally int32 or int64)
intp    Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8    Byte (-128 to 127)
int16   Integer (-32768 to 32767)
int32   Integer (-2147483648 to 2147483647)
int64   Integer (-9223372036854775808 to 9223372036854775807)
uint8   Unsigned integer (0 to 255)
uint16  Unsigned integer (0 to 65535)
uint32  Unsigned integer (0 to 4294967295)
uint64  Unsigned integer (0 to 18446744073709551615)
float_  Shorthand for float64.
float16 Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32 Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64 Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_    Shorthand for complex128.
complex64   Complex number, represented by two 32-bit floats (real and imaginary components)
complex128  Complex number, represented by two 64-bit floats (real and imaginary components)

https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations

**Some Basic Functions which we can perform in NUMPY**

In [41]:
zero = np.zeros((2,5)) #this will create a matrix whos size is given by user and put all the elements as zero = 0.

In [42]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
rang = np.arange(15) #this will give us a matrix which have numbers in range 0 to 15 and in python we are not going to count the last element.

In [37]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
lspace = np.linspace(1,5,8)

In [45]:
lspace

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In linspace (1,5,8) this function will divide it and the starting is from = 1 and the ending is from = 5 and the number of elements which it will give is = 8

In [56]:
ide = np.identity(50) # As we know the matrix identity function create a matrix which have only elements on diagonls.

In [47]:
print(ide)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [48]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [55]:
emp = np.empty((11,12))#this will create an empty array which can have some values,
                       #on that array we can assign any sepcific values.

In [54]:
emp

array([[0.00000000e+000, 3.01380044e-322, 0.00000000e+000,
        2.17213117e-314, 2.38247220e-314, 4.94065646e-324,
                    nan,             nan, 2.38233847e-314,
                    nan, 2.17213116e-314, 2.38241688e-314],
       [2.33419537e-313, 0.00000000e+000, 0.00000000e+000,
        2.38233847e-314, 2.12199579e-314, 2.15488522e-314,
        2.38241688e-314, 1.48539705e-313, 2.76676762e-322,
        0.00000000e+000, 2.38241688e-314, 2.12199579e-314],
       [2.15488522e-314, 2.38241688e-314, 6.36598737e-314,
        5.53353523e-322, 0.00000000e+000, 4.24399158e-314,
        2.12199579e-314, 2.15488525e-314, 2.38241688e-314,
        1.90979621e-313, 8.30030285e-322, 1.48219694e-323],
       [2.38233847e-314, 2.12199579e-314, 2.15488526e-314,
        2.38241689e-314, 1.90979621e-313, 1.10670705e-321,
        2.38241674e-314, 2.38233847e-314, 6.36598738e-314,
        2.15488530e-314, 2.38241689e-314, 1.90979621e-313],
       [1.38338381e-321, 9.88131292e-323, 2.38233847

In [51]:
emp_like = np.empty_like(lspace) 

In [52]:
emp_like

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [57]:
arr = np.arange(99)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
 arr.reshape(3,33) #this'll reshape the array as per the demand.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

Axis : on dimensional array have only one axis which is axis 0. If the array is two dimensional array then there are two axis - axis : 0[for row], axis : 1[for column].

# Axis

In [93]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [94]:
arr = np.array(x)

In [95]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [96]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [97]:
arr.sum(axis = 0)

array([12,  8,  9])

In [98]:
arr.sum(axis = 1)

array([ 6, 15,  8])

In [99]:

arr.flat
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [100]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [101]:
arr.ndim

2

In [102]:
arr.size

9

In [103]:
arr.shape

(3, 3)

In [104]:
arr.nbytes #this will show how much the bits does consume by the array.

72

WE HAVE TO PREPARE OURSELEF WITH THE GOOD KNOWLEDGE OF *ATTRIBUTES* AND *ARGUMENTS*

In [105]:
one = np.array([1,2,3,44,5,66,777])

In [106]:
one

array([  1,   2,   3,  44,   5,  66, 777])

In [107]:
one.argmin()#Output will come one the behalf of indexing

0

In [108]:
one.argmax()#Output will come one the behalf of indexing

6

In [109]:
one.argsort()#Output will come one the behalf of indexing

array([0, 1, 2, 4, 3, 5, 6])

In [110]:
one.argmin()

0

In [111]:
arr.argmax(axis = 0)

array([2, 1, 1])

In [112]:
 arr.argmax(axis = 1)

array([2, 2, 0])

In [115]:
arr.argsort(axis = 1) #this will sort on the behalf of column and show the output in indexing.

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [114]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [116]:
arr.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [117]:
 arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [118]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [130]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [140]:
arr1 = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [141]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [142]:
arr + arr1

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10,  4,  3]])

In [143]:
 [200,100]+[5,4] 

[200, 100, 5, 4]

In [144]:
arr*arr1

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21,  3,  0]])

In [146]:
arr.sum()

29

In [148]:
arr.min()


0

In [149]:
arr.max()

7

In [150]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [152]:
type(np.where(arr>5))

tuple

# Just focus on the ATTRIBUTES and METHODS.